### ISSUE TITLE
速度约快40%，代码行数少66%

### ISSUE THREAD

**Issue by davidli218** [Mizuno-Mashiro/Python-RPSLS#1]
My code:

```python
import random

dic = {0: 'rock', 1: 'spock', 2: 'paper', 3: 'lizard', 4: 'scissors'}

player = int(5 * random.random())
com = int(5 * random.random())

print(f"YOUR CHOICE: {dic[player]}\nCOMPUTER'S CHOICE: {dic[com]}")
print(f"{'YOU' if (player - com) % 5 < 3 else 'COMPUTER'} WIN" if player ^ com else "DRAW")
```

**Comment by ning-bao** [comment]
It seems after testing my code has a better performance using the list probably :) ? (in this case list is faster than division? Not 100% sure about that >_<). But your code is definitely more precise. Thank you so much
貌似測試后發現性能方面還是我的list比較快(不確定是不是在這個情況下list比除法更快) :) 但是代碼長度上確實縮短了許多 謝謝您
![2020-09-09 (2)](https://user-images.githubusercontent.com/62197506/92549112-29918500-f28b-11ea-8497-116e10e225c4.png)
![2020-09-09 (3)](https://user-images.githubusercontent.com/62197506/92549117-2b5b4880-f28b-11ea-908d-b56d04a416ea.png)

**Comment by davidli218** [comment]
That is quiet strange. This is my test result
![2020-09-09 17-47-01 的屏幕截图](https://user-images.githubusercontent.com/56788328/92585325-667b6d00-f2c7-11ea-8c91-33e216b895ea.png)
![2020-09-09 17-54-31 的屏幕截图](https://user-images.githubusercontent.com/56788328/92585330-67ac9a00-f2c7-11ea-8087-3b39d019f11a.png)
